# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac72adb3d763f7e6b29a4c774e80eea1fd8871f3c96699f399ef80770bb263c4e64e05b4c5e18596bff304262889d7efe3474e97d29261ec2b027fd77283d72

test:
  secret_key_base: ac34f456972a3059d7431bfe8946acf4eb6e56757538cb95888f32d5521c4ebd7e26f7640ee63a974af73abf911753f41a5e09724d3b6dac4d3a4955053a4e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
